export class AppColors {
  static readonly BLUE: string = '#4F7CFF'
  static readonly BLUE_50: string = '#F3F6FF'

  static readonly INDIGO_50: string = '#EEF2FF'

  static readonly WHITE: string = '#FFFFFF'

  static readonly GRAY_BLUE_50: string = '#F6F7FB'
  static readonly GRAY_50: string = '#F9FAFB'
  static readonly GRAY_100: string = '#F3F4F6'
  static readonly GRAY_200: string = '#E5E7EB'
  static readonly GRAY_400: string = '#9CA3AF'
  static readonly GRAY_500: string = '#6B7280'
  static readonly GRAY_800: string = '#1F2937'
  static readonly GRAY_900: string = '#111827'

  static readonly GREEN: string = '#22C55E'
  static readonly GREEN_50: string = '#F0FDF4'
  static readonly GREEN_100: string = '#DCFCE7'

  static readonly RED: string = '#EF4444'
  static readonly RED_100: string = '#FEE2E2'
}
