export const STORE_NAME: string = 'time_plan_store'

export const TASKS_KEY: string = 'plan_tasks'
export const TASK_NEXT_ID_KEY: string = 'plan_tasks_next_id'

export const NOTES_KEY: string = 'note_items'
export const NOTE_NEXT_ID_KEY: string = 'note_items_next_id'

export const HABITS_KEY: string = 'habit_items'
export const HABIT_NEXT_ID_KEY: string = 'habit_items_next_id'

export const THEME_KEY: string = 'app_theme_mode'

export const FOCUS_RECORDS_KEY: string = 'focus_records'
export const FOCUS_NEXT_ID_KEY: string = 'focus_records_next_id'
